### PR TITLE
Include "allow-multiple-definition" LD flag for Android ARM

### LINKED ISSUE #34: Linking fails with "multiple definitions of ..." error when compiling for Android ARM
As per the conversation on Ethereum's gitter, when trying to compiling go-ethereum for Android ARM it fails with several, "multiple definitions of...", errors:

https://gitter.im/ethereum/go-ethereum?at=5696f30ec391361d48eaf738

### PR DESCRIPTION
**Pull request by dan-turner**
Closes #34

### CODE REVIEW

**Comment by karalabe** [comment]
I was wondering why I didn't catch this one :) Turns out it was fixed by Go 1.6, and since I was using that for the Android builds this slipped through. Thanks for catching it!

**Comment by karalabe** [comment]
Strange, but this doesn't seem to fix it for me currently. I get the same linker errors.

**Comment by dan-turner** [comment]
Even after publishing the new docker image? I must confess I didn't test it
because I would have had to create my own docker images and change all the
references to it.

**Comment by karalabe** [comment]
You need to rebuild only the base image and one of the release images to do it :)

```
docker build --tag karalabe/xgo-base ./docker/base
docker build --tag karalabe/xgo-1.5.3 ./docker/go-1.5.3
```

Then you can specify to xgo the version you require explicitly so that it doesn't require all the meta images to be built (e.g. `--go=1.5.3` or `GO=1.5.3` (in make)) :)

**Comment by karalabe** [comment]
Still, android builds most definitely worked well, so I screwed something up bad..

**Comment by karalabe** [comment]
Ok, I think docker screwed something up. I did a ton of rebuilds and now everything works fine. Will probably push out the images and then clean up everything and do a recheck to make sure.

**Comment by dan-turner** [comment]
Nice!

**Comment by karalabe** [comment]
I've also polished this a bit so that the workaround is used only for Go 1.5 and below. Since Go 1.6 fixes the issue and `android/arm64` and `android/386` are only supported in Go 1.6+, there's no point in adding the workaround to these platforms. https://github.com/karalabe/xgo/commit/a9a3fc21f548db17501d8d73140f3358fb52c701

**Pull request merged**
