### PR TITLE
Execute custom user script before the compile step

### PR DESCRIPTION
**Pull request by tsg**
Another PR in the direction of extensibility, not sure if this fits with the project's goals. It adds a `-before-build` parameter which accepts a script which will be executed after cloning but before running the compilers.

This can be used, for example, to get and compile dependencies for which the steps taken by the `build_deps.sh` script are not enough.

### CODE REVIEW

**Comment by tsg** [comment]
I made this on top of #20. If you prefer me to rebase on master, happy to comply.

**Comment by tsg** [comment]
Rebased on to pof #21.

**Comment by dustinblackman** [comment]
:+1: Having this included would be a great help compared to having to fork the images to add dependencies.

**Comment by tsg** [comment]
Closing since this is really old by now.

**Pull request closed without merging**
