### PR TITLE
The --remote option was failing with error complaining "Please tell me who you are."

### LINKED ISSUE #50: The --remote option is failing with error complaining "Please tell me who you are."
Hello,

I'm trying to use xgo to compile a fork of go-ethereum and initially hit this issue:

Command:
`xgo -branch dan --targets=android-15/* github.com/dan-turner/go-ethereum/cmd/geth`

Output:
```
Bootstrapping android-15/arm...
Compiling for android-15/arm...
package github.com/dan-turner/go-ethereum/cmd/geth
	imports github.com/ethereum/go-ethereum/internal/debug: use of internal package not allowed
package github.com/dan-turner/go-ethereum/cmd/geth
	imports github.com/ethereum/go-ethereum/internal/web3ext: use of internal package not allowed
2016/05/18 04:59:19 Failed to cross compile package: exit status 1.
```

I then discovered the `--remote` option which sounded exactly like what I needed, but there seems to be a slight bug without it complaining about a lack of git config:

Command:
`xgo --remote=https://github.com/dan-turner/go-ethereum.git -branch dan --targets=android-15/* github.com/ethereum/go-ethereum/cmd/geth`
Error:
```
Switching over to remote https://github.com/dan-turner/go-ethereum.git...
From https://github.com/dan-turner/go-ethereum
 + 8ea3c88...9e323d6 master     -> origin/master  (forced update)
 * [new branch]      dan        -> origin/dan

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@9a9f35565a35.(none)')
2016/05/18 05:04:43 Failed to cross compile package: exit status 128.
```

### PR DESCRIPTION
**Pull request by dan-turner**
Closes #50

### CODE REVIEW

**Comment by dan-turner** [comment]
G'day mate, have you had a chance to take a look at this one?

**Comment by karalabe** [comment]
Woops, completely forgotten about this one. Sorry, looking now :)

**Comment by karalabe** [comment]
LGTM :+1:

**Comment by dan-turner** [comment]
Nice! Cheers mate :)

**Pull request merged**
