### PR TITLE
Update with golang 1.9.0 + 1.9.1

### LINKED ISSUE #89: Support for go 1.9
Hello,  

I am using xgo to build and release several of my projects and would like to start using go 1.9 features and fixes, unfortunately when I try with `xgo --go 1.9` I get:
```
Checking for required docker image karalabe/xgo-1.9... not found!
```
I am not sure what is involved in getting a new xgo supported version, hopefully it is not too hard, or perhaps you can point me in a direction to help provide you a PR?

Thanks for xgo, it has been extremely useful!

### PR DESCRIPTION
**Pull request by sofuture**
Golang 1.9.0 and 1.9.1 docker images.

Fixes #89 
Includes #90 from @coryb

### CODE REVIEW

**Comment by apparentlymart** [comment]
The 1.9.1 dockerfile here worked for me and successfully built an application that requires >= 1.9.0.

**Comment by sofuture** [comment]
@karalabe any chance of merging?

**Comment by karalabe** [comment]
Whoops, forgot about xgo and I don't look at github notifications, merging now. Thanks!

**Comment by fatih** [comment]
@karalabe can you also look at https://github.com/karalabe/xgo/pull/96 please. It's about version `1.9.2`

**Comment by karalabe** [comment]
Yes, doing that too, just needs a minor fix that's missing from the PR.

**Pull request merged**
