### PR TITLE
Change deps-cache path to inside home instead of a temp folder

### LINKED ISSUE #33: Dependency fails to extract
I am trying to use `xgo` to cross compile ethereum for Android, but I'm running in to some issues.  I've fallen back to just trying the simplest of examples from your Readme.md and it too is failing.  If I run the following:

```
xgo --deps=https://gmplib.org/download/gmp/gmp-6.1.0.tar.bz2  \
    --targets=windows/* github.com/ethereum/go-ethereum/cmd/geth
```

I get:
```
Checking docker installation...
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

Checking for required docker image karalabe/xgo-latest... found.
Downloading new dependency: https://gmplib.org/download/gmp/gmp-6.1.0.tar.bz2...
New dependency cached: /var/folders/q8/x7qc7x2j01gdjyzzdskblcph0000gq/T/xgo-cache/gmp-6.1.0.tar.bz2.
Cross compiling github.com/ethereum/go-ethereum/cmd/geth...
Fetching main repository github.com/ethereum/go-ethereum/cmd/geth...
github.com/ethereum/go-ethereum (download)
cat: /deps-cache/gmp-6.1.0.tar.bz2: No such file or directory

bzip2: Compressed file ends unexpectedly;
	perhaps it is corrupted?  *Possible* reason follows.
bzip2: Inappropriate ioctl for device
	Input file = (stdin), output file = (stdout)

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.

tar: Child returned status 2
tar: Error is not recoverable: exiting now
2016/01/13 16:04:20 Failed to cross compile package: exit status 2.
```

If I run the suggested integrity test as suggested:
`sudo bzip2 -tvv /var/folders/q8/x7qc7x2j01gdjyzzdskblcph0000gq/T/xgo-cache/gmp-6.1.0.tar.bz2`

I get:
```
/var/folders/q8/x7qc7x2j01gdjyzzdskblcph0000gq/T/xgo-cache/gmp-6.1.0.tar.bz2: 
    [1: huff+mtf rt+rld]
    [2: huff+mtf rt+rld]
    [3: huff+mtf rt+rld]
    [4: huff+mtf rt+rld]
    [5: huff+mtf rt+rld]
    [6: huff+mtf rt+rld]
    [7: huff+mtf rt+rld]
    [8: huff+mtf rt+rld]
    [9: huff+mtf rt+rld]
    [10: huff+mtf rt+rld]
    [11: huff+mtf rt+rld]
    [12: huff+mtf rt+rld]
    [13: huff+mtf rt+rld]
    [14: huff+mtf rt+rld]
    [15: huff+mtf rt+rld]
    [16: huff+mtf rt+rld]
    [17: huff+mtf rt+rld]
    ok
```

### PR DESCRIPTION
**Pull request by dan-turner**
Closes #33

### CODE REVIEW

**Comment by karalabe** [comment]
I'm really curious as to why this happens on OSX. I would expect that 1) the temp folder should be `/tmp` and not `/var/folder/...` and 2) the temp folder should stay there indefinitely, whereas in your case it seems to be deleted. Are you using some more exotic file system layout by any chance?

Btw, the idea of moving the dependency cache into the home folder is probably fine as Ubuntu also has some issues where from time to time it doesn't delete it on reboot (it should clean tmp every restart), but rather reowns it by root, causing xgo to hit a permission error on next compilation.

**Comment by dan-turner** [comment]
Nothing exotic about my file system. The problem first presented on my work
laptop. Suspecting it may be somehow related to the work image I then tried
my personal laptop, a new, freshly installed El Capitan MacBook and saw the
same.

The file doesn't get deleted persay. If I run it a second time it detects
that the file was already downloaded. But if I change in to its directly
and try and do an 'ls' I get a permission denied. Also have to sudo to
delete it from memory.

**Comment by karalabe** [comment]
Hmm, thanks for that, found the permission bug :) I set the cache folder permission to `751`... the correct one is `0751` :D

**Comment by karalabe** [comment]
I've extended this a bit so that is has a few fallback paths to select from if `HOME` is not set https://github.com/karalabe/xgo/commit/75c37e116e9ca9c0212aed8cd36461eb2b4f2d24#diff-f579eb9647b08b4f207b210335cc344dR28

**Pull request merged**
